export const COLORS = {
  bg: '#ffffff',
  bgAlt: '#f9fafb',
  surface: '#ffffff',
  surfaceActive: '#eff6ff',
  surfaceAlt: '#f3f4f6',
  border: '#e5e7eb',
  borderStrong: '#d1d5db',
  primary: '#2563eb',
  primaryPressed: '#1d4ed8',
  primarySoft: '#eff6ff',
  primaryBorder: '#bfdbfe',
  secondary: '#e5e7eb',
  secondaryPressed: '#d1d5db',
  text: '#111827',
  textHeading: '#374151',
  textBody: '#1f2937',
  textMuted: '#6b7280',
  textFaint: '#9ca3af',
  white: '#ffffff',
  error: '#f87171',
  errorSoft: 'rgba(248, 113, 113, 0.1)',
  errorBorder: 'rgba(248, 113, 113, 0.3)',
  danger: '#fecaca',
  dangerText: '#7f1d1d',
  dangerStrong: '#dc2626',
  overlay: 'rgba(0, 0, 0, 0.4)',
  sceneBg: '#eef1f5',
  gold: '#fbbf24',
  goldSoft: 'rgba(251, 191, 36, 0.15)',
  goldBorder: 'rgba(251, 191, 36, 0.3)',
  green: '#34d399',
  greenSoft: 'rgba(52, 211, 153, 0.15)',
} as const;

export const RADII = {
  sm: 6,
  md: 8,
  lg: 10,
  xl: 16,
  pill: 20,
} as const;

export const commonStyles = {
  screen: {
    flex: 1,
    width: '100%',
    backgroundColor: COLORS.bg,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.bg,
    paddingHorizontal: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.bgAlt,
  },
  backButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: RADII.sm,
    backgroundColor: COLORS.secondary,
  },
  backButtonPressed: {
    backgroundColor: COLORS.secondaryPressed,
  },
  backButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textHeading,
  },
  headerTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    textAlign: 'center',
  },
  primaryButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: RADII.md,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
  },
  primaryButtonPressed: {
    backgroundColor: COLORS.primaryPressed,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: RADII.sm,
    backgroundColor: COLORS.secondary,
  },
  secondaryButtonPressed: {
    backgroundColor: COLORS.secondaryPressed,
  },
  secondaryButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textHeading,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.bg,
  },
  statusText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.textMuted,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textHeading,
    marginBottom: 12,
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  label: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textHeading,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    height: 44,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: RADII.md,
    paddingHorizontal: 12,
    backgroundColor: COLORS.bgAlt,
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 10,
  },
  multilineInput: {
    height: 70,
    paddingTop: 10,
    textAlignVertical: 'top',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  chip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: COLORS.surfaceAlt,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
  },
  chipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textHeading,
  },
  chipTextActive: {
    color: COLORS.white,
  },
  smallButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: RADII.sm,
    backgroundColor: COLORS.secondary,
    marginLeft: 6,
  },
  deleteSmallButton: {
    backgroundColor: COLORS.danger,
  },
  smallButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textHeading,
  },
  scroll: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  emptyText: {
    textAlign: 'center',
    color: COLORS.textMuted,
    fontSize: 14,
    paddingVertical: 30,
  },
} as const;